all: 1 2 3 

#compiler
CC=g++

#option gived to developer
CFLAGS= -g -Wall -lncurses -std=c++11

1: 1.cpp
	g++ -g -o 1 1.cpp -lncurses

2: 2.cpp
	${CC} ${CFLAGS} -o 2 2.cpp 

3: 3.cpp
	${CC} ${CFLAGS} -o 3 3.cpp 

compile:
