
#compiler
CC=g++

#option gived to developer
CFLAGS= -g -Wall -lncurses -std=c++11

all: 1 2 3 

1: 1.cpp
	g++ -g -o 1 1.cpp -lncurses

2: 2.cpp
	${CC}  -o 2 2.cpp ${CFLAGS}

3: 3.cpp
	${CC} -o 3 3.cpp ${CFLAGS}

